
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
# Style/BlockDelimiters:
#   Enabled: false
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
# Style/MultilineBlockLayout:
#   Enabled: false

Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 12
